# This is a basic workflow to help you get started with Actions
name: A workflow for ensuring credentials are not in file
on: push
jobs:
  build:
    name: Cred Checker
    runs-on: ubuntu-latest
    steps:        
       - uses: actions/checkout@master
       - name: John Folia trufflehog-actions-scan
         uses: johnfolia/trufflehog-actions-scan@master
         with:
           branch: ${GITHUB_REF##*/}
           scanArguments: "--regex --entropy=False --max_depth=50" # Add custom options here*
           #test runs
